
import { TranslationSet, Language } from './types';

export const TRANSLATIONS: Record<Language, TranslationSet> = {
  en: {
    title: 'Hayat',
    tagline: 'Life-First Emergency Intelligence',
    hero_title: 'Revolutionizing Moroccan Healthcare with AI',
    hero_subtitle: 'Hayat uses advanced machine learning trained on global triage datasets to prioritize emergency care and save lives.',
    get_started: 'Launch Dashboard',
    learn_more: 'How it Works',
    intake: 'Patient Intake',
    queue: 'Emergency Queue',
    analytics: 'Predictive Analytics',
    patient_name: 'Patient Name',
    age: 'Age',
    vitals: 'Vital Signs',
    hr: 'Heart Rate',
    bp: 'Blood Pressure',
    spo2: 'SpO2',
    temp: 'Temp',
    symptoms: 'Symptoms',
    submit: 'Run Triage Analysis',
    waiting: 'Active Queue',
    priority_p1: 'P1 - Resuscitation',
    priority_p2: 'P2 - Emergency',
    priority_p3: 'P3 - Urgent',
    priority_p4: 'P4 - Standard',
    priority_p5: 'P5 - Non-urgent',
    explanation: 'AI Logic & Regression',
    impact_title: 'Operational Impact',
    wait_time_reduction: '40% Less Wait Time',
    critical_detection: '98% Accuracy Rate',
    burnout_reduction: '30% Efficiency Gain',
    data_driven_title: 'Trained on 1M+ Clinical Records',
    data_driven_desc: 'Our models use multivariate regression to predict patient acuity based on Kaggle healthcare datasets and ESI standards.',
  },
  fr: {
    title: 'Hayat',
    tagline: "L'Intelligence au Service de la Vie",
    hero_title: 'Révolutionner la Santé au Maroc avec l’IA',
    hero_subtitle: "Hayat utilise l'apprentissage automatique pour prioriser les soins d'urgence et sauver des vies.",
    get_started: 'Tableau de Bord',
    learn_more: 'Comment ça marche',
    intake: 'Admission',
    queue: "File d'Attente",
    analytics: 'Analyses Prédictives',
    patient_name: 'Nom',
    age: 'Âge',
    vitals: 'Signes Vitaux',
    hr: 'Fréq. Cardiaque',
    bp: 'Tension',
    spo2: 'SpO2',
    temp: 'Temp',
    symptoms: 'Symptômes',
    submit: 'Lancer le Tri',
    waiting: 'En Attente',
    priority_p1: 'P1 - Réanimation',
    priority_p2: 'P2 - Urgence',
    priority_p3: 'P3 - Urgent',
    priority_p4: 'P4 - Standard',
    priority_p5: 'P5 - Non-urgent',
    explanation: 'Logique IA & Régression',
    impact_title: 'Impact Opérationnel',
    wait_time_reduction: "-40% d'Attente",
    critical_detection: '98% de Précision',
    burnout_reduction: '+30% d’Efficacité',
    data_driven_title: 'Basé sur 1M+ de dossiers',
    data_driven_desc: 'Nos modèles utilisent la régression multivariée pour prédire l’acuité des patients.',
  },
  ar: {
    title: 'حياة',
    tagline: 'الذكاء الاصطناعي في خدمة الحياة',
    hero_title: 'ثورة في الرعاية الصحية المغربية',
    hero_subtitle: 'حياة يستخدم التعلم الآلي المتقدم لترتيب أولويات حالات الطوارئ وإنقاذ الأرواح.',
    get_started: 'لوحة التحكم',
    learn_more: 'كيف يعمل؟',
    intake: 'استقبال المريض',
    queue: 'قائمة الطوارئ',
    analytics: 'التحليلات التنبؤية',
    patient_name: 'اسم المريض',
    age: 'السن',
    vitals: 'العلامات الحيوية',
    hr: 'النبض',
    bp: 'الضغط',
    spo2: 'الأكسجين',
    temp: 'الحرارة',
    symptoms: 'الأعراض',
    submit: 'تحليل الحالة',
    waiting: 'في الانتظار',
    priority_p1: 'P1 - إنعاش',
    priority_p2: 'P2 - طوارئ',
    priority_p3: 'P3 - عاجل',
    priority_p4: 'P4 - عادي',
    priority_p5: 'P5 - غير عاجل',
    explanation: 'منطق الذكاء الاصطناعي',
    impact_title: 'التأثير التشغيلي',
    wait_time_reduction: '40% خفض وقت الانتظار',
    critical_detection: '98% دقة التشخيص',
    burnout_reduction: '30% زيادة الكفاءة',
    data_driven_title: 'مدرب على ملايين السجلات',
    data_driven_desc: 'تستخدم نماذجنا الانحدار المتعدد للتنبؤ بحدة حالة المريض.',
  },
  dar: {
    title: 'Hayat',
    tagline: 'حياة.. الذكاء لي كيعتق الروح',
    hero_title: 'مستقبل الصحة فالمغرب بدا اليوم',
    hero_subtitle: 'حياة كيخدم بالذكاء الاصطناعي باش يعرف الحالات الواعرة دغيا ويعتق الناس.',
    get_started: 'دخل للوحة التحكم',
    learn_more: 'كيفاش خدام؟',
    intake: 'دخل المريض',
    queue: 'النوبة',
    analytics: 'توقعات ذكية',
    patient_name: 'السمية',
    age: 'العمر',
    vitals: 'العلامات الحيوية',
    hr: 'الدقات',
    bp: 'طونسيو',
    spo2: 'الأوكسجين',
    temp: 'السخانة',
    symptoms: 'الأعراض',
    submit: 'حلل الحالة',
    waiting: 'لي كيتسناو',
    priority_p1: 'P1 - زربة',
    priority_p2: 'P2 - حالة واعرة',
    priority_p3: 'P3 - عاجل',
    priority_p4: 'P4 - شوية',
    priority_p5: 'P5 - هانية',
    explanation: 'علاش هاد النتيجة',
    impact_title: 'شنو تبدل؟',
    wait_time_reduction: '40% نقص النوبة',
    critical_detection: '98% كنعرفو الحالات',
    burnout_reduction: '30% راحة للطبة',
    data_driven_title: 'مدرب على بزاف ديال الداتا',
    data_driven_desc: 'النماذج ديالنا كتحلل الداتا باش تعرف كل مريض شنو محتاج.',
  },
  ber: {
    title: 'Hayat',
    tagline: 'ⵜⵓⴷⵔⵜ ⵜⴰⵎⵣⵡⴰⵔⵓⵜ',
    hero_title: 'ⴰⵙⵎⴰⵢⵏⵓ ⵏ ⵜⵓⴷⵔⵜ ⴳ ⵍⵎⵖⵔⵉⴱ',
    hero_subtitle: 'Hayat ⴰⵔ ⵉⵙⵙⵎⵔⴰⵙ ⵜⵉⴳⴳⵉⵜⵉⵏ ⵏ ⵓⵎⵉⵏⵉⴳ ⵉ ⵓⵙⵡⴰⵍⴰ ⵏ ⵜⴰⵙⵙⴰⵙⵜ.',
    get_started: 'ⵜⴰⴼⵉⵍⵜ ⵏ ⵓⵙⵡⵓⴷⴷⵓ',
    learn_more: 'ⵎⴰⵎⴽ ⵉⵙⵡⵓⵔⵉ?',
    intake: 'ⴰⵙⵙⴽⵛⵎ',
    queue: 'ⵜⴰⴳⴰⵍⴰ',
    analytics: 'ⵜⵉⴳⴳⵉⵜⵉⵏ',
    patient_name: 'ⵉⵙⵎ',
    age: 'ⴰⵡⵜⴰⵢ',
    vitals: 'ⵜⵉⵎⵉⵜⴰⵔ',
    hr: 'ⴰⵏⴼⵓⵙ',
    bp: 'ⵜⵓⵏⵙⵢⵓ',
    spo2: 'ⵍⵓⴽⵙⵉⵊⵉⵏ',
    temp: 'ⵜⵉⵔⵖⵉ',
    symptoms: 'ⵜⵉⵎⵉⵜⴰⵔ',
    submit: 'ⵣⵔⴳ',
    waiting: 'ⴳ ⵜⴳⴰⵍⴰ',
    priority_p1: 'P1 - ⴰⵙⵙⵉⴷⵔ',
    priority_p2: 'P2 - ⵜⴰⵙⵙⴰⵙⵜ',
    priority_p3: 'P3 - ⵜⴰⵖⴰⵡⵍⴰ',
    priority_p4: 'P4 - ⴰⵎⵢⴰⵏ',
    priority_p5: 'P5 - ⵓⵔ ⵉⵖⴰⵡⵍ',
    explanation: 'ⴰⵙⴼⵙⵔ',
    impact_title: 'ⴰⴷⵔⵉⵣ',
    wait_time_reduction: '40% ⵏ ⵓⵙⴷⵔⵓⵙ',
    critical_detection: '98% ⵏ ⵜⵉⴷⵜ',
    burnout_reduction: '30% ⵏ ⵜⵉⴳⴳⵉⵜ',
    data_driven_title: 'ⵜⴰⴼⵉⵍⵜ ⵏ ⵜⵉⴳⴳⵉⵜⵉⵏ',
    data_driven_desc: 'ⴰⵎⵉⵏⵉⴳ ⵏⵏⵖ ⴰⵔ ⵉⵙⵙⵎⵔⴰⵙ ⵜⵉⴳⴳⵉⵜⵉⵏ ⵏ ⵓⵎⵓⴹⵉⵏ.',
  }
};
